data:
  train_files: /mnt/data/wuxinrui/BAAI_cot_sft_data/with_COT/AGD_affordance_train_common_1336/AGD_affordance_train_common_1336.parquet
  val_files: hiyouga/math12k@test
  prompt_key: problem
  answer_key: answer
  image_key: images
  max_prompt_length: 50000
  max_response_length: 50000
  rollout_batch_size: 128
  val_batch_size: 1024
  format_prompt: ./examples/format_prompt/r1v_format.jinja
  shuffle: true
  seed: 1
  max_pixels: 4194304
  min_pixels: 262144

algorithm:
  adv_estimator: grpo
  disable_kl: false
  use_kl_loss: true
  kl_penalty: low_var_kl
  kl_coef: 1.0e-2

worker:
  actor:
    global_batch_size: 128
    micro_batch_size_per_device_for_update: 4
    micro_batch_size_per_device_for_experience: 16
    max_grad_norm: 1.0
    padding_free: true
    model:
      model_path: /mnt/lyc/wuxinrui/RoboBrain-2/HF_Models/BAAI-RoboBrain2.0-7B
      enable_gradient_checkpointing: true
      trust_remote_code: false
      freeze_vision_tower: false
    optim:
      lr: 1.0e-6
      weight_decay: 1.0e-2
      strategy: adamw  # {adamw, adamw_bf16}
      lr_warmup_ratio: 0.0
    fsdp:
      enable_full_shard: true
      enable_cpu_offload: false
      enable_rank0_init: true
    offload:
      offload_params: true  # true: more CPU memory; false: more GPU memory
      offload_optimizer: true  # true: more CPU memory; false: more GPU memory

  rollout:
    n: 5
    temperature: 1.0
    top_p: 0.99
    gpu_memory_utilization: 0.6
    enforce_eager: false
    enable_chunked_prefill: false
    tensor_parallel_size: 1
    max_num_batched_tokens: 120000
    limit_images: 0
    val_override_config:
      temperature: 0.5
      n: 1

  ref:
    fsdp:
      enable_full_shard: true
      enable_cpu_offload: true  # true: more CPU memory; false: more GPU memory
      enable_rank0_init: true
    offload:
      offload_params: false

  # reward:
  #   reward_type: batch
  #   score_function: reason_with_in_limit
  reward:
    reward_type: batch
    reward_function: ./examples/reward_function/math.py:compute_score

trainer:
  total_episodes: 15
  project_name: robobrain_7b_3ratio_RL_v1
  experiment_name: robobrain_7b_3ratio_RL_v1
  logger: ["console", "wandb"]
  nnodes: 1
  n_gpus_per_node: 8
  val_freq: -1  # -1 to disable
  val_before_train: true
  val_only: false
  val_generations_to_log: 3
  save_freq: 5  # -1 to disable
  save_limit: 3  # -1 to disable
  save_checkpoint_path: null
  load_checkpoint_path: null
